config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :restaurants do
    resources :reviews
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_one_attached :main_image

  scope :by_rating, -> { order(rating: :desc) }

  def update_rating(restaurant)
    arr = []
    restaurant.reviews.each { |review| arr << review.rating }
    restaurant.rating = (arr.inject{ |sum, el| sum + el }.to_f / arr.size).round(1)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  scope :most_recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments, dependent: :destroy
  has_many :restaurants, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def update_ratings
    Restaurant.all.each do |restaurant|
      restaurant.update_rating(restaurant)
      restaurant.save
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :update_ratings

  def index
    @restaurants = Restaurant.by_rating.paginate(page: params[:page], per_page: 3)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :update_ratings
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @reviews = @restaurant.reviews.most_recent
    @new_review = Review.new if current_user
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.includes(:reviews).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :main_image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new(params[:review].permit(:rating, :comment))
    @review.user = current_user
    @review.save

    email_info = { user: current_user,
                   review: @review,
                   restaurant: @restaurant
                 }
    RestaurantOwnerNotifierMailer.inform(email_info, @restaurant.user.email).deliver_now
    flash[:notice] = "Thank you so much for taking the time to leave us review."

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@restaurant)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/index.html.erb
<div class="container mt-5">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-3">
        <div class="card text-center">
          <div class="card-header">
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= restaurant.name %></h5>
            <p class="card-text">Rating: <%= restaurant.rating %></p>
          </div>
          <div class="card-footer text-muted">
            <%= restaurant.created_at.strftime("%d %b %Y") %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="mt-5">
    <%= will_paginate @restaurants %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Bark</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Restaurants", restaurants_path, class: 'nav-link' %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Account", edit_user_registration_path %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Sign Up", new_user_registration_path %>
          <%= link_to "Login", new_user_session_path %>
        </li>
      <% end %>
    </ul>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <title>Devchallenge</title>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/nav' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :main_image %>
    <%= form.file_field :main_image %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.user_id %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Show', restaurant %></td>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
  <%= link_to 'Back', restaurants_path %>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @restaurant.user_id %>
</p>

<%= image_tag @restaurant.main_image, width: 350 %>

<%= render 'reviews/form' %>
<h2>Reviews</h2>
<div class="mb-3 h4">
  Average Rating:
  <%= @restaurant.rating %>
</div>
<%= render @reviews if @reviews.any? %>

app/views/reviews/_form.html.erb
<div class="card card-body">
  <div class="card-title">
    Submit a Review
  </div>
  <%= form_with(model: [@restaurant, Review.new], local: true) do |form| %>
    <div class="form-group">
      <label for="exampleFormControlSelect1">5 Star Rating</label>
      <%= form.select(:rating, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]], class: 'form-control') %>
    </div>

    <div class="form-group">
      <label for="comment">Comment</label>
      <%= form.text_field :comment, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/reviews/_review.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= review.user.email %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Rating: <%= review.rating %></h6>
    <p class="card-text"><%= review.comment %></p>
    <%= link_to 'Delete', restaurant_review_path(@restaurant, review), method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>